name: emmet
description: Point, Explore, Build.
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.9.4+5
  permission_handler: ^11.0.1
  permission_handler_web: ^0.0.2
  google_fonts: ^6.2.1
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  intl: ^0.19.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  flutter_vision: ^1.1.4
  sqflite: ^2.3.3+1
  path_provider: ^2.1.4
  shimmer: ^3.0.0
  webview_flutter: ^4.9.0
  shelf: ^1.4.1
  shelf_static: ^1.1.3
  font_awesome_flutter: ^10.7.0
  google_generative_ai: ^0.4.6
  flutter_speed_dial: ^7.0.0
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/model/
    - assets/database/
    - assets/buildinginstructions/
    - assets/buildinginstructions/apps/
    - assets/buildinginstructions/css/
    - assets/buildinginstructions/js/
    - assets/buildinginstructions/ldraw_parts/
    - assets/buildinginstructions/ldraw_parts/8/
    - assets/buildinginstructions/ldraw_parts/48/
    - assets/buildinginstructions/ldraw_parts/s/
    - assets/buildinginstructions/ldraw_unofficial/
    - assets/buildinginstructions/ldraw_unofficial/48/
    - assets/buildinginstructions/ldraw_unofficial/s/
    - assets/buildinginstructions/models/
    - assets/buildinginstructions/official/
    - assets/buildinginstructions/official/p/
    - assets/buildinginstructions/official/parts/
    - assets/buildinginstructions/omr_icons/
    - assets/buildinginstructions/tests/
    - assets/buildinginstructions/textures/
    - assets/buildinginstructions/textures/cube/
    - assets/buildinginstructions/textures/materials/
    - assets/buildinginstructions/unofficial/p/
    - assets/buildinginstructions/unofficial/parts/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/LatoRegular.ttf
          weight: 400
        - asset: assets/fonts/LatoBold.ttf
          weight: 700
        - asset: assets/fonts/LatoExtraBold.ttf
          weight: 800
        - asset: assets/fonts/LatoMedium.ttf
          weight: 500
