name: emmet
description: Point, Explore, Build.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  camera: ^0.11.0+1
  permission_handler: ^11.0.1
  permission_handler_web: ^0.0.2
  google_fonts: ^6.2.1
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  intl: ^0.19.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  google_maps_flutter: ^2.3.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Lato
      fonts: 
        - asset: assets/fonts/LatoRegular.ttf
          weight: 400
        - asset: assets/fonts/LatoBold.ttf
          weight: 700
        - asset: assets/fonts/LatoExtraBold.ttf
          weight: 800
        - asset: assets/fonts/LatoMedium.ttf
          weight: 500
